name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies and run tests
        run: yarn --ignore-engines
      - run: yarn test --coverage --watchAll=false
      - name: Upload coverage report to Codacy  
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
